### ISSUE TITLE
tap file loading not supported with cspect

### ISSUE THREAD

**Issue by maziac** [darenm/SpectrumNextTutorials#3]
> load: The .nex, .sna (or .tap) file to load. <== Changed

For cspect you can only load nex and sna files. No tap (this is only possible with zesarux).

**Comment by ped7g** [comment]
but tap can be still uploaded to the card image file, then the NextZXOS will deal with it, so ... I didn't check, if this refers to direct launch of cspect, or overall target capabilities. I think overall TAP is viable, as long as card image is used.

**Comment by maziac** [comment]
You don't have to launch CSpect with a tap file. 
What I meant was the DeZog launch.json "load" parameter. 

DeZog reads these files by itself and transfer them to CSpect by writing into memory. The CSpect Debug API has no means to load nex, sna or tap.
Here DeZog supports only sna and nex, no tap.
